#!/bin/bash

# ---
# Helper script to create a "differential" Lockbox.
# ---
#
# Dependencies (Debian): coreutils findutils sed grep ostree

# shellcheck disable=SC2155
set -e -o pipefail

# DEBUG can be passed in the environment (values: "yes" or "" (empty))
DEBUG=${DEBUG:-}
SIM_PULL_ROUNDS_DEFAULT=${SIM_PULL_ROUNDS_DEFAULT:-40}

# Default values for optional arguments.
#
# The following boolean variables should be set to "yes" or "":
# STATIC_DELTAS_ENABLED, VERBOSE, FORCE
#
VERBOSE=""
FORCE=""
STATIC_DELTAS_ENABLED="yes"
GEN_STATIC_DELTAS_ARGS=""
SIM_PULL_ROUNDS=${SIM_PULL_ROUNDS_DEFAULT}

yellow() {
    printf '\033[01;33m%s\033[0m' "$*"
}

fatal() {
    echo "ERROR: $*" >&2
    exit 2
}

error() {
    echo "ERROR: $*" >&2
}

info() {
    if [ "$1" = "--header" ]; then
        shift
        echo ""
        echo "== $(yellow "$*")"
    else
        echo "$*"
    fi
}

debug() {
    if [ "${DEBUG}" = "yes" ]; then
        echo "DEBUG: $*"
    fi
}

usage() {
    cat <<EOF
Usage: make-diff-lockbox LOCKBOX_A LOCKBOX_B LOCKBOX_DIFF
                  [-h|--help]
                  [-v|--verbose]
                  [--with-static-deltas|--without-static-deltas]
                  [--gen-static-deltas-args GEN_STATIC_DELTAS_ARGS]
                  [--sim-pull-rounds SIM_PULL_ROUNDS]

Create a "differential" Lockbox (one containing the differences for going
from LOCKBOX_A to LOCKBOX_B).

Note: this script handles only the OSTree part of the Lockbox.

Positional arguments:
  LOCKBOX_A       Path to source Lockbox (input).
  LOCKBOX_B       Path to target Lockbox (input).
  LOCKBOX_DIFF    Path to differential Lockbox to be produced (output).

Optional arguments:
  --with-static-deltas/--without-static-deltas
                  Enable (default) or disable the generation of static deltas.
  --gen-static-deltas-args GEN_STATIC_DELTAS_ARGS
                  Additional arguments to "ostree static-delta generate".
  --sim-pull-rounds SIM_PULL_ROUNDS
                  Number of OSTree simulated "pull" rounds to execute in
                  order to determine the files accessed during an update;
                  default: ${SIM_PULL_ROUNDS_DEFAULT}.
EOF
}

simulate_update() {
    local src_ostree="${1?src_ostree required}"
    local src_commit="${2?src_commit required}"
    local dst_ostree="${3?dst_ostree required}"
    local dst_commit="${4?dst_commit required}"
    local update_log="${5?update_log required}"

    for ((round=1; round<=SIM_PULL_ROUNDS; round++)); do
        echo "## Round #${round}" >> "${update_log}"

        local tmp_ostree=$(mktemp -t -d "tmp.sim-bareusr-repo.XXXXXXXXXX")
        function ostree_tmp() { ostree --repo="${tmp_ostree}" "$@"; }

        echo "[${round}/${SIM_PULL_ROUNDS}] Pulling commit into OSTree repo and collecting logs."
        ostree_tmp init  --mode=bare-user
        ostree_tmp pull-local "${src_ostree}" "${src_commit}" > /dev/null
        ostree_tmp pull-local "${dst_ostree}" "${dst_commit}" \
               --require-static-deltas \
               --verbose >> "${update_log}" 2>&1

        rm -fr "${tmp_ostree}"
    done

    if [ "${DEBUG}" = "yes" ]; then
        info "Update logs:"
        sed -e 's/^/> /' "${update_log}"
    fi
}

drop_ostree_objects() {
    local ostree_repo="${1?ostree required}"
    local exclude_list="${2?exclude list file path required}"
    find "${ostree_repo}/objects" -type f | \
        grep -vF -f "${exclude_list}" | xargs -n5 rm -f ${VERBOSE:+${DEBUG:+-v}}
}

get_commit() {
    local ostree="$1"
    local commit_files=$(find "${ostree}" -name \*.commit)
    local commit_count=$(echo "${commit_files}" | wc -l)

    if [ "${commit_count}" -ne 1 ]; then
        fatal "Could not determine a unique commit in '${ostree}'."
    fi

    # shellcheck disable=SC2001
    echo "${commit_files}" | sed -e 's#.*/\([0-9a-f][0-9a-f]\)/\(.*\)\.commit#\1\2#'
}

# Output of make_diff_ostree_sd() on success.
OSTREE_DIFF_REPO=""

# Make a differential OSTree repo (static-deltas case).
make_diff_ostree_sd() {
    local ostree_a="${1?path for ostree A required}"
    local ostree_b="${2?path for ostree B required}"

    # Replacement for the B repo whether deltas are used or not.
    local ostree_b_proxy="${ostree_b}"

    # ostree-ab-full: OSTree repo containing commits A, B and deltas.
    local ostree_ab_full=$(mktemp -t -d "tmp.ostree-ab-full.XXXXXXXXXX")

    # ostree-ab-diff: differential OSTree repo (A to B).
    local ostree_ab_diff=$(mktemp -t -d "tmp.ostree-ab-diff.XXXXXXXXXX")

    # ostree-update-log: Store simulated OSTree update logs.
    local update_log=$(mktemp -t "tmp.ostree-update-log.XXXXXXXXXX")

    # ostree-exclude-list: Files not to be removed from diff repository.
    local exclude_list=$(mktemp -t "tmp.ostree-exclude-list.XXXXXXXXXX")

    function make_diff_ostree_cleanup() {
        debug 'Cleaning up for make_diff_ostree_sd()...'
        rm -fr ${DEBUG:+-v} "${ostree_ab_full}" || true
        rm -fr ${DEBUG:+-v} "${ostree_ab_diff}" || true
        rm -fr ${DEBUG:+-v} "${update_log}"     || true
        rm -fr ${DEBUG:+-v} "${exclude_list}"   || true
    }
    
    trap "make_diff_ostree_cleanup" EXIT

    local commit_a=$(get_commit "${ostree_a}")
    local commit_b=$(get_commit "${ostree_b}")
    debug "ostree_ab_full=${ostree_ab_full}"
    debug "ostree_ab_diff=${ostree_ab_diff}"

    # ---
    # Populate ostree-ab-full:
    # ---
    info --header "Populate OSTree A+B repository"
    info "Populating OSTree A+B repository with commits:"
    info "* A: ${commit_a}"
    info "* B: ${commit_b}"

    function ostree_ab() { ostree --repo="${ostree_ab_full}" "$@"; }

    cp -a "${ostree_b}/." "${ostree_ab_full}/"
    ostree_ab remote add "other" "file://$(realpath "${ostree_a}")" --no-gpg-verify
    ostree_ab pull other "${commit_a}"
    ostree_ab remote delete "other"

    info --header "Generate static-delta"
    info "Generating static-delta from A to B on OSTree A+B repository."
    # shellcheck disable=SC2086
    ostree_ab static-delta generate \
              --from="${commit_a}" "${commit_b}" ${GEN_STATIC_DELTAS_ARGS}

    info --header "Generate summary file"
    info "Generating/updating summary file in OSTree A+B repository."
    ostree_ab summary -u
    info "List of static-deltas in repository:"
    ostree_ab summary -v

    ostree_b_proxy="${ostree_ab_full}"

    # ---
    # Simulate an update from A to B and collect logs:
    # ---
    info --header "Simulate updates"
    info "Simulating updates to determine necessary files."
    simulate_update "${ostree_a}" "${commit_a}" \
                    "${ostree_b_proxy}" "${commit_b}" \
                    "${update_log}"

    if [ "${VERBOSE}" = "yes" ]; then
        info "Objects accessed during update (prefixed by access count):"
        sed -nE \
            -e 's/^.*starting fetch of.* ([0-9a-f]{32,64}\.[a-z]{3,15})( .*|$)/\1/p' "${update_log}" \
            | sort | uniq -c | sed -e 's/^/> /'
    fi

    sed -nE \
        -e 's/^.*starting fetch of.* ([0-9a-f]{2})([0-9a-f]{30,62}\.[a-z]{3,15})( .*|$)/\2/p' "${update_log}" \
        | sort | uniq > "${exclude_list}"

    # ---
    # Generate diff repo based on B by dropping unaccessed files on the simulation:
    # ---
    info --header "Generate differential OSTree repository"
    info "Generating OSTree repository with unaccessed files deleted."
    cp -a "${ostree_b_proxy}/." "${ostree_ab_diff}/"
    drop_ostree_objects "${ostree_ab_diff}" "${exclude_list}"

    # At this point all ops succeded so we move the temporary result in ostree-ab-diff to
    # ostree-diff-repo which can then be consumed by the caller (which is responsible for
    # deleting that directory).
    OSTREE_DIFF_REPO=$(mktemp -u -t -d "tmp.ostree-diff-repo.XXXXXXXXXX")
    mv "${ostree_ab_diff}" "${OSTREE_DIFF_REPO}"

    make_diff_ostree_cleanup

    trap - EXIT
}

# Make a differential OSTree repo (non static-deltas case).
make_diff_ostree_no_sd() {
    local ostree_a="${1?path for ostree A required}"
    local ostree_b="${2?path for ostree B required}"

    # ostree-ab-diff: differential OSTree repo (A to B).
    local ostree_ab_diff=$(mktemp -t -d "tmp.ostree-ab-diff.XXXXXXXXXX")

    # ostree-{drop,keep}-list: Files to be droped/kept in the diff repo.
    local drop_list=$(mktemp -t "tmp.ostree-drop-list.XXXXXXXXXX")
    local keep_list=$(mktemp -t "tmp.ostree-keep-list.XXXXXXXXXX")

    function make_diff_ostree_cleanup() {
        debug 'Cleaning up for make_diff_ostree_no_sd()...'
        rm -fr ${DEBUG:+-v} "${ostree_ab_diff}" || true
        rm -fr ${DEBUG:+-v} "${drop_list}" || true
        rm -fr ${DEBUG:+-v} "${keep_list}" || true
    }

    trap "make_diff_ostree_cleanup" EXIT

    # ---
    # Determine differences:
    # ---
    info --header "Determine differences between repos"

    local ostree_a_full=$(realpath "${ostree_a}")
    (
        # Go over all objects in B checking if they are present on A:
        # If an object is present on A then it can be deleted from B.
        cd "${ostree_b}/objects/"
        find . \
             -type f \
             -exec bash -c "
                       test -e \"${ostree_a_full}/objects/{}\" && \
                       echo \"{}\" | sed -e 's#\./../##' -e 's#\.filez#\.file#' >> \"${drop_list}\" || \
                       echo \"{}\" | sed -e 's#\./../##' -e 's#\.filez#\.file#' >> \"${keep_list}\"
                   " \;
    )

    if [ "${VERBOSE}" = "yes" ]; then
        info "Objects present in repo A (can be deleted):"
        cat "${drop_list}" | sed -e 's/^/> /'
        info "Objects only present in repo B (will be kept):"
        cat "${keep_list}" | sed -e 's/^/> /'
    fi
    info "Number of objects present in repo A (to be deleted): $(wc -l "${drop_list}" | cut -d' ' -f1)"
    info "Number of objects only present in repo B (to be kept): $(wc -l "${keep_list}" | cut -d' ' -f1)"

    # ---
    # Generate diff repo based on B by dropping unnecessary files:
    # ---
    info --header "Generate differential OSTree repository"
    info "Generating OSTree repository with unnecessary files deleted."
    cp -a "${ostree_b}/." "${ostree_ab_diff}/"
    drop_ostree_objects "${ostree_ab_diff}" "${keep_list}"

    # At this point all ops succeded so we move the temporary result in ostree-ab-diff to
    # ostree-diff-repo which can then be consumed by the caller (which is responsible for
    # deleting that directory).
    OSTREE_DIFF_REPO=$(mktemp -u -t -d "tmp.ostree-diff-repo.XXXXXXXXXX")
    mv "${ostree_ab_diff}" "${OSTREE_DIFF_REPO}"

    make_diff_ostree_cleanup

    trap - EXIT
}

make_diff_lockbox() {
    local lockbox_a="${1?path for lockbox A required}"
    local lockbox_b="${2?path for lockbox B required}"
    local lockbox_diff="${3?path for output lockbox required}"

    [ -d "${lockbox_a}" ] || fatal "Lockbox directory '${lockbox_a}' does not exist."
    [ -d "${lockbox_b}" ] || fatal "Lockbox directory '${lockbox_b}' does not exist."

    if [ -d "${lockbox_diff}" ] && [ "${FORCE}" != "yes" ]; then
        fatal "Lockbox '${lockbox_diff}' already exists; aborting."
    fi

    local ostree_a="${lockbox_a}/images/ostree"
    local ostree_b="${lockbox_b}/images/ostree"

    [ -d "${ostree_a}" ] || fatal "OSTree directory '${ostree_a}' does not exist."
    [ -d "${ostree_b}" ] || fatal "OSTree directory '${ostree_b}' does not exist."

    if [ "${STATIC_DELTAS_ENABLED}" = "yes" ]; then
        make_diff_ostree_sd "${ostree_a}" "${ostree_b}"
    else
        make_diff_ostree_no_sd "${ostree_a}" "${ostree_b}"
    fi

    # ---
    # Store differential OSTree repo into final Lockbox:
    # ---
    info --header "Generate final Lockbox"
    info "Storing final Lockbox into '${lockbox_diff}'."
    rm -fr "${lockbox_diff}"
    cp -a "${lockbox_b}" "${lockbox_diff}"
    rm -fr "${lockbox_diff}/images/ostree"
    cp -a "${OSTREE_DIFF_REPO}" "${lockbox_diff}/images/ostree"
    rm -fr "${OSTREE_DIFF_REPO}"

    # ---
    # Show some stats:
    # ---
    info --header "Statistics"
    local ostree_a_size=$(du -sk "${ostree_a}" | cut -f1)
    local ostree_b_size=$(du -sk "${ostree_b}" | cut -f1)
    local ostree_d_size=$(du -sk "${lockbox_diff}/images/ostree" | cut -f1)

    info "Size of OSTree repository in Lockbox A: ${ostree_a_size} kB"
    info "Size of OSTree repository in Lockbox B: ${ostree_b_size} kB"
    info "Size of differential (A to B) OSTree repository in output Lockbox: ${ostree_d_size} kB"
}

if [ $# -eq 0 ]; then
    usage
    echo -e "\nERROR: No arguments have been passed." >&2
    exit 1
fi

OPTIONS="h,f,v"
LONGOPTIONS="help,force,verbose,with-static-deltas,without-static-deltas,gen-static-deltas-args:,sim-pull-rounds:"
PARSED=$(getopt --options="${OPTIONS}" --longoptions="${LONGOPTIONS}" --name "$0" -- "$@")
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
    # Exit with error if getopt has complained about wrong arguments.
    exit 1
fi

# Evaluate the parsed arguments:
eval set -- "${PARSED}"

while true; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -f|--force)
            FORCE="yes"
            shift
            ;;
        -v|--verbose)
            VERBOSE="yes"
            shift
            ;;
        --with-static-deltas)
            STATIC_DELTAS_ENABLED="yes"
            shift
            ;;
        --without-static-deltas)
            STATIC_DELTAS_ENABLED=""
            shift
            ;;
        --gen-static-deltas-args)
            GEN_STATIC_DELTAS_ARGS="$2"
            shift 2
            ;;
        --sim-pull-rounds)
            SIM_PULL_ROUNDS="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "ERROR: Unexpected option: $1" >&2
            usage
            exit 1
            ;;
    esac
done

# At this point $@ contains only the positional arguments.
if [ $# -ne 3 ]; then
    usage
    echo -e "\nERROR: Exactly 3 positional arguments are required." >&2
    exit 1
fi

make_diff_lockbox "$@"
